export const GAME_SETTINGS = {
    PLAYER_RADIUS: 30,
    PROJECTILE_RADIUS: 5,
    PROJECTILE_SPEED: 7,
    ENEMY_SPAWN_INTERVAL: 1000,
    ENEMY_MIN_RADIUS: 10,
    ENEMY_MAX_RADIUS: 30,
    ENEMY_SPEED: 2,
    PARTICLE_COUNT: 8,
    PARTICLE_FRICTION: 0.99,
    PARTICLE_FADE_SPEED: 0.01
};